In [1]:
import pandas as pd
import numpy as np
import re

In [9]:
df = pd.read_csv('data/raw/PODM_3295_CTAB_20260424232953.csv', sep=';')

In [10]:
df = df.iloc[:, 1:-1]

df.columns.values[0] = "region"

In [11]:
display(df.head())

,region,ogółem;2002;[-],ogółem;2003;[-],ogółem;2004;[-],ogółem;2005;[-],ogółem;2006;[-],ogółem;2007;[-],ogółem;2008;[-],ogółem;2009;[-],ogółem;2010;[-],...,ogółem;2015;[-],ogółem;2016;[-],ogółem;2017;[-],ogółem;2018;[-],ogółem;2019;[-],ogółem;2020;[-],ogółem;2021;[-],ogółem;2022;[-],ogółem;2023;[-],ogółem;2024;[-]
0,DOLNOŚLĄSKIE,"1593,7","1635,9","1616,3","1597,2","1597,1","1624,3","1669,9","1673,2","1728,6",...,"1958,3","2006,9","2076,6","2140,6","2209,2","2283,9","2397,2","2516,6","2621,6","2723,6"
1,KUJAWSKO-POMORSKIE,"1427,8","1462,0","1404,1","1408,5","1404,1","1413,0","1437,5","1360,0","1370,8",...,"1477,9","1497,9","1526,8","1561,0","1626,8","1739,2","1812,6","1867,2","1929,6","1995,2"
2,LUBELSKIE,"1134,0","1163,4","1114,4","1105,0","1113,0","1117,0","1137,2","1147,4","1191,1",...,"1304,1","1324,4","1365,3","1409,5","1463,3","1594,7","1674,2","1751,9","1820,0","1882,9"
3,LUBUSKIE,"1499,4","1504,3","1514,1","1547,0","1593,4","1603,9","1533,1","1525,9","1577,2",...,"1731,5","1759,5","1800,3","1831,2","1920,3","2047,8","2147,0","2220,9","2302,0","2388,2"
4,ŁÓDZKIE,"1428,8","1475,6","1489,3","1515,2","1471,1","1473,7","1486,6","1358,3","1424,6",...,"1577,7","1612,3","1654,1","1690,3","1763,4","1866,0","1953,5","2035,0","2106,1","2176,0"

In [12]:
print(df.columns)

Index(['region', 'ogółem;2002;[-]', 'ogółem;2003;[-]', 'ogółem;2004;[-]',
       'ogółem;2005;[-]', 'ogółem;2006;[-]', 'ogółem;2007;[-]',
       'ogółem;2008;[-]', 'ogółem;2009;[-]', 'ogółem;2010;[-]',
       'ogółem;2011;[-]', 'ogółem;2012;[-]', 'ogółem;2013;[-]',
       'ogółem;2014;[-]', 'ogółem;2015;[-]', 'ogółem;2016;[-]',
       'ogółem;2017;[-]', 'ogółem;2018;[-]', 'ogółem;2019;[-]',
       'ogółem;2020;[-]', 'ogółem;2021;[-]', 'ogółem;2022;[-]',
       'ogółem;2023;[-]', 'ogółem;2024;[-]'],
      dtype='object')

In [13]:
import pandas as pd
import re

df_long = df.melt(
    id_vars=["region"],
    var_name="raw_col",
    value_name="liczba_pomiotow_gospodarczych"
)

def parse(col):
    # usuń jednostkę [ - ] (niepotrzebna)
    col = re.sub(r"\[.*?\]", "", col)
    
    parts = col.split(";")
    
    # rok
    year = next((p for p in parts if re.fullmatch(r"\d{4}", p)), None)
    
    return pd.Series({
        "rok": int(year) if year else None,
        "typ": parts[0]  # "ogółem"
    })

df_long = pd.concat(
    [df_long, df_long["raw_col"].apply(parse)],
    axis=1
)

df_long = df_long.drop(columns=["raw_col", "typ"])

In [14]:
display(df_long)

                  region liczba_pomiotow_gospodarczych   rok
0           DOLNOŚLĄSKIE                        1593,7  2002
1     KUJAWSKO-POMORSKIE                        1427,8  2002
2              LUBELSKIE                        1134,0  2002
3               LUBUSKIE                        1499,4  2002
4                ŁÓDZKIE                        1428,8  2002
..                   ...                           ...   ...
363              ŚLĄSKIE                        2205,0  2024
364       ŚWIĘTOKRZYSKIE                        2002,1  2024
365  WARMIŃSKO-MAZURSKIE                        1903,3  2024
366        WIELKOPOLSKIE                        2541,6  2024
367   ZACHODNIOPOMORSKIE                        2714,5  2024

[368 rows x 3 columns]

In [16]:
df_long.to_csv("data/processed/liczba_podmiotow_gospodarczych.csv", index=False)

In [17]:
df_long.describe()

               rok
count   368.000000
mean   2013.000000
std       6.642281
min    2002.000000
25%    2007.000000
50%    2013.000000
75%    2019.000000
max    2024.000000

In [ ]:
df_long.missing_values = df_long.isnull().sum()
display(df_long.missing_values)

C:\Users\user\AppData\Local\Temp\ipykernel_25804\278907725.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_long.missing_values = df_long.isnull().sum()

region                           0
liczba_pomiotow_gospodarczych    0
rok                              0
dtype: int64

: