In [38]:
import pandas as pd
import numpy as np
import re

In [39]:
df = pd.read_excel("data/raw/RYNE_2671_XTAB_20260425131033.xlsx", 
                   header=[0, 1], 
                   sheet_name="TABLICA"
                   )

In [40]:
display(df.head())

                 Kod               Nazwa   ogółem                             \
  Unnamed: 0_level_1  Unnamed: 1_level_1     2003     2004     2005     2006
0                NaN                 NaN  [osoba]  [osoba]  [osoba]  [osoba]
1                0.0              POLSKA        -        -        -  1139446
2           200000.0        DOLNOŚLĄSKIE        -        -        -    86092
3           400000.0  KUJAWSKO-POMORSKIE        -        -        -    78618
4           600000.0           LUBELSKIE        -        -        -    74349

                                       ...  \
      2007     2008     2009     2010  ...
0  [osoba]  [osoba]  [osoba]  [osoba]  ...
1   787243   501339   488898   568687  ...
2    51601    33312    33675    39469  ...
3    55711    38853    38300    41897  ...
4    57679    40540    37238    38575  ...

  bezrobotni w liczbie ludności w wieku produkcyjnym                           \
                                                2016 2017 2018 2019 2020 2021
0                                                [%]  [%]  [%]  [%]  [%]  [%]
1                                                2.3  1.9  1.6  1.4  1.8  1.9
2                                                1.8  1.5  1.3  1.2  1.5  1.6
3                                                3.2  2.9  2.5  2.1  2.7  2.7
4                                                3.3  2.8  2.5  2.3  2.9  2.8


  2022 2023 2024 2025
0  [%]  [%]  [%]  [%]
1  1.5  1.4  1.4    -
2  1.2  1.2  1.2    -
3    2  1.9  1.9    -
4  2.3  2.1    2    -

[5 rows x 48 columns]

In [41]:
# remove first column "numer"

df = df.iloc[:, 1:]

In [42]:
df.columns = [
    "_".join([str(x) for x in col if pd.notna(x)])
    for col in df.columns
]

df.columns.values[0] = "region" # rename first column to "region"

df.columns = df.columns.str.replace(" ", "_")

In [43]:
df = df.drop(index=0) # usuwanie wierwsza z "[osoba]"

In [44]:
display(df.head())

,region,ogółem_2003,ogółem_2004,ogółem_2005,ogółem_2006,ogółem_2007,ogółem_2008,ogółem_2009,ogółem_2010,ogółem_2011,...,bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2016,bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2017,bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2018,bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2019,bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2020,bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2021,bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2022,bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2023,bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2024,bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2025
1,POLSKA,-,-,-,1139446,787243,501339,488898,568687,685237,...,2.3,1.9,1.6,1.4,1.8,1.9,1.5,1.4,1.4,-
2,DOLNOŚLĄSKIE,-,-,-,86092,51601,33312,33675,39469,46362,...,1.8,1.5,1.3,1.2,1.5,1.6,1.2,1.2,1.2,-
3,KUJAWSKO-POMORSKIE,-,-,-,78618,55711,38853,38300,41897,51481,...,3.2,2.9,2.5,2.1,2.7,2.7,2,1.9,1.9,-
4,LUBELSKIE,-,-,-,74349,57679,40540,37238,38575,48560,...,3.3,2.8,2.5,2.3,2.9,2.8,2.3,2.1,2,-
5,LUBUSKIE,-,-,-,30833,19515,12427,12986,14146,16012,...,1.7,1.2,1.2,0.9,1.2,1.2,0.8,0.7,0.8,-

In [45]:
print(df.columns.tolist())

['region', 'ogółem_2003', 'ogółem_2004', 'ogółem_2005', 'ogółem_2006', 'ogółem_2007', 'ogółem_2008', 'ogółem_2009', 'ogółem_2010', 'ogółem_2011', 'ogółem_2012', 'ogółem_2013', 'ogółem_2014', 'ogółem_2015', 'ogółem_2016', 'ogółem_2017', 'ogółem_2018', 'ogółem_2019', 'ogółem_2020', 'ogółem_2021', 'ogółem_2022', 'ogółem_2023', 'ogółem_2024', 'ogółem_2025', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2003', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2004', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2005', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2006', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2007', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2008', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2009', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2010', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2011', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2012', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2013', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2014', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2015', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2016', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2017', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2018', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2019', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2020', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2021', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2022', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2023', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2024', 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym_2025']

In [46]:
df_long = df.melt(
    id_vars=['region'], 
    var_name='full_key', 
    value_name='wartosc'
)

In [47]:
df_long = df_long.replace("-", np.nan)

C:\Users\user\AppData\Local\Temp\ipykernel_11572\4097166025.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_long = df_long.replace("-", np.nan)

In [56]:
display(df_long)

,region,full_key,wartosc,zmienna,rok
0,POLSKA,ogółem_2003,NaN,ogółem,2003
1,DOLNOŚLĄSKIE,ogółem_2003,NaN,ogółem,2003
2,KUJAWSKO-POMORSKIE,ogółem_2003,NaN,ogółem,2003
3,LUBELSKIE,ogółem_2003,NaN,ogółem,2003
4,LUBUSKIE,ogółem_2003,NaN,ogółem,2003
...,...,...,...,...,...
777,ŚLĄSKIE,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,NaN,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,2025
778,ŚWIĘTOKRZYSKIE,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,NaN,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,2025
779,WARMIŃSKO-MAZURSKIE,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,NaN,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,2025
780,WIELKOPOLSKIE,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,NaN,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,2025
781,ZACHODNIOPOMORSKIE,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,NaN,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,2025

In [49]:
pattern = r'^(.*)_(\d{4})$'

def parse_cols(col_name):
    match = re.match(pattern, col_name)
    if match:
        return match.groups() # Zwraca (nazwa_zmiennej, rok)
    return (None, None)

# Stosujemy rozbicie
df_long[['zmienna', 'rok']] = df_long['full_key'].apply(
    lambda x: pd.Series(parse_cols(x))
)

In [50]:
display(df_long)

,region,full_key,wartosc,zmienna,rok
0,POLSKA,ogółem_2003,NaN,ogółem,2003
1,DOLNOŚLĄSKIE,ogółem_2003,NaN,ogółem,2003
2,KUJAWSKO-POMORSKIE,ogółem_2003,NaN,ogółem,2003
3,LUBELSKIE,ogółem_2003,NaN,ogółem,2003
4,LUBUSKIE,ogółem_2003,NaN,ogółem,2003
...,...,...,...,...,...
777,ŚLĄSKIE,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,NaN,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,2025
778,ŚWIĘTOKRZYSKIE,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,NaN,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,2025
779,WARMIŃSKO-MAZURSKIE,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,NaN,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,2025
780,WIELKOPOLSKIE,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,NaN,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,2025
781,ZACHODNIOPOMORSKIE,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,NaN,bezrobotni_w_liczbie_ludności_w_wieku_produkcy...,2025

In [51]:
# 3. Pivot - robimy unikalne wiersze dla [region + rok]
# a zmienne 'ogółem' i 'bezrobotni...' trafiają do osobnych kolumn
df_final = df_long.pivot_table(
    index=['region', 'rok'],
    columns='zmienna',
    values='wartosc',
    aggfunc='first'
).reset_index()

In [52]:
# Wynik
display(df_final)

zmienna,region,rok,bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym,ogółem
0,DOLNOŚLĄSKIE,2006,NaN,86092.0
1,DOLNOŚLĄSKIE,2007,NaN,51601.0
2,DOLNOŚLĄSKIE,2008,NaN,33312.0
3,DOLNOŚLĄSKIE,2009,NaN,33675.0
4,DOLNOŚLĄSKIE,2010,NaN,39469.0
...,...,...,...,...
335,ŚWIĘTOKRZYSKIE,2021,2.6,18087.0
336,ŚWIĘTOKRZYSKIE,2022,2.1,13958.0
337,ŚWIĘTOKRZYSKIE,2023,1.9,12783.0
338,ŚWIĘTOKRZYSKIE,2024,1.9,12511.0
339,ŚWIĘTOKRZYSKIE,2025,NaN,13782.0

In [53]:
df_final.to_csv("data/processed/wolne_miejsca_pracy.csv", index=False)

In [54]:
df_final.describe()

zmienna  bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym        ogółem
count                                           187.000000   3.400000e+02
mean                                              2.003209   6.431399e+04
std                                               0.822526   1.334645e+05
min                                               0.600000   4.199000e+03
25%                                               1.400000   1.907600e+04
50%                                               1.900000   3.088300e+04
75%                                               2.500000   4.859425e+04
max                                               4.600000   1.139446e+06

In [55]:
df_final.missing_values = df_final.isnull().sum()
display(df_final.missing_values)

C:\Users\user\AppData\Local\Temp\ipykernel_11572\3170999439.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_final.missing_values = df_final.isnull().sum()

zmienna
region                                                  0
rok                                                     0
bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym    153
ogółem                                                  0
dtype: int64