In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("data/raw/LUDN_1356_XTAB_20260424000018.xlsx", 
                   header=[0, 1, 2], 
                   sheet_name="TABLICA"
                   )

In [3]:
display(df.head())

                 Kod               Nazwa zameldowania ogółem           \
  Unnamed: 0_level_1  Unnamed: 1_level_1              ogółem
  Unnamed: 0_level_2  Unnamed: 1_level_2                1999     2000
0                NaN                 NaN             [osoba]  [osoba]
1                0.0              POLSKA              311080   284456
2           200000.0        DOLNOŚLĄSKIE               23789    20087
3           400000.0  KUJAWSKO-POMORSKIE               18407    16552
4           600000.0           LUBELSKIE               18316    15895

                                                         ... saldo migracji  \
                                                         ...        kobiety
      2001     2002     2003     2004     2005     2006  ...           2016
0  [osoba]  [osoba]  [osoba]  [osoba]  [osoba]  [osoba]  ...        [osoba]
1   269282   293235   310878   312441   306845   338499  ...              0
2    20385    21088    19993    20837    20199    25945  ...           1416
3    15349    16971    18265    18461    17839    19422  ...           -894
4    14171    15559    16371    16174    15718    16544  ...          -2471

                                                                           \

      2017     2018     2019     2020     2021     2022     2023     2024
0  [osoba]  [osoba]  [osoba]  [osoba]  [osoba]  [osoba]  [osoba]  [osoba]
1        0        0        0        0        0        0        0        0
2     1471     1566     2277     1772     1650     1909     1900     1821
3     -849    -1380    -1562    -1139    -1098     -849    -1149    -1031
4    -2801    -3220    -3603    -2522    -2817    -2547    -2567    -2742



      2025
0  [osoba]
1        -
2        -
3        -
4        -

[5 rows x 569 columns]

In [4]:
# remove first column "numer"

df = df.iloc[:, 1:]

In [5]:
df.columns = [
    "_".join([str(x) for x in col if pd.notna(x)])
    for col in df.columns
]

df.columns.values[0] = "region" # rename first column to "region"

df.columns = df.columns.str.replace(" ", "_")

In [6]:
df = df.drop(index=0) # usuwanie wierwsza z "[osoba]"

In [7]:
display(df.head())

,region,zameldowania_ogółem_ogółem_1999,zameldowania_ogółem_ogółem_2000,zameldowania_ogółem_ogółem_2001,zameldowania_ogółem_ogółem_2002,zameldowania_ogółem_ogółem_2003,zameldowania_ogółem_ogółem_2004,zameldowania_ogółem_ogółem_2005,zameldowania_ogółem_ogółem_2006,zameldowania_ogółem_ogółem_2007,...,saldo_migracji_kobiety_2016,saldo_migracji_kobiety_2017,saldo_migracji_kobiety_2018,saldo_migracji_kobiety_2019,saldo_migracji_kobiety_2020,saldo_migracji_kobiety_2021,saldo_migracji_kobiety_2022,saldo_migracji_kobiety_2023,saldo_migracji_kobiety_2024,saldo_migracji_kobiety_2025
1,POLSKA,311080,284456,269282,293235,310878,312441,306845,338499,360885,...,0,0,0,0,0,0,0,0,0,-
2,DOLNOŚLĄSKIE,23789,20087,20385,21088,19993,20837,20199,25945,26565,...,1416,1471,1566,2277,1772,1650,1909,1900,1821,-
3,KUJAWSKO-POMORSKIE,18407,16552,15349,16971,18265,18461,17839,19422,20087,...,-894,-849,-1380,-1562,-1139,-1098,-849,-1149,-1031,-
4,LUBELSKIE,18316,15895,14171,15559,16371,16174,15718,16544,18316,...,-2471,-2801,-3220,-3603,-2522,-2817,-2547,-2567,-2742,-
5,LUBUSKIE,8705,7794,7407,7406,8571,8642,8658,9645,10204,...,-417,-568,-545,-719,-521,-615,-477,-394,-543,-

In [8]:
print(df.columns.tolist())

['region', 'zameldowania_ogółem_ogółem_1999', 'zameldowania_ogółem_ogółem_2000', 'zameldowania_ogółem_ogółem_2001', 'zameldowania_ogółem_ogółem_2002', 'zameldowania_ogółem_ogółem_2003', 'zameldowania_ogółem_ogółem_2004', 'zameldowania_ogółem_ogółem_2005', 'zameldowania_ogółem_ogółem_2006', 'zameldowania_ogółem_ogółem_2007', 'zameldowania_ogółem_ogółem_2008', 'zameldowania_ogółem_ogółem_2009', 'zameldowania_ogółem_ogółem_2010', 'zameldowania_ogółem_ogółem_2011', 'zameldowania_ogółem_ogółem_2012', 'zameldowania_ogółem_ogółem_2013', 'zameldowania_ogółem_ogółem_2014', 'zameldowania_ogółem_ogółem_2015', 'zameldowania_ogółem_ogółem_2016', 'zameldowania_ogółem_ogółem_2017', 'zameldowania_ogółem_ogółem_2018', 'zameldowania_ogółem_ogółem_2019', 'zameldowania_ogółem_ogółem_2020', 'zameldowania_ogółem_ogółem_2021', 'zameldowania_ogółem_ogółem_2022', 'zameldowania_ogółem_ogółem_2023', 'zameldowania_ogółem_ogółem_2024', 'zameldowania_ogółem_ogółem_2025', 'zameldowania_ogółem_mężczyźni_1999', 'zameldowania_ogółem_mężczyźni_2000', 'zameldowania_ogółem_mężczyźni_2001', 'zameldowania_ogółem_mężczyźni_2002', 'zameldowania_ogółem_mężczyźni_2003', 'zameldowania_ogółem_mężczyźni_2004', 'zameldowania_ogółem_mężczyźni_2005', 'zameldowania_ogółem_mężczyźni_2006', 'zameldowania_ogółem_mężczyźni_2007', 'zameldowania_ogółem_mężczyźni_2008', 'zameldowania_ogółem_mężczyźni_2009', 'zameldowania_ogółem_mężczyźni_2010', 'zameldowania_ogółem_mężczyźni_2011', 'zameldowania_ogółem_mężczyźni_2012', 'zameldowania_ogółem_mężczyźni_2013', 'zameldowania_ogółem_mężczyźni_2014', 'zameldowania_ogółem_mężczyźni_2015', 'zameldowania_ogółem_mężczyźni_2016', 'zameldowania_ogółem_mężczyźni_2017', 'zameldowania_ogółem_mężczyźni_2018', 'zameldowania_ogółem_mężczyźni_2019', 'zameldowania_ogółem_mężczyźni_2020', 'zameldowania_ogółem_mężczyźni_2021', 'zameldowania_ogółem_mężczyźni_2022', 'zameldowania_ogółem_mężczyźni_2023', 'zameldowania_ogółem_mężczyźni_2024', 'zameldowania_ogółem_mężczyźni_2025', 'zameldowania_ogółem_kobiety_1999', 'zameldowania_ogółem_kobiety_2000', 'zameldowania_ogółem_kobiety_2001', 'zameldowania_ogółem_kobiety_2002', 'zameldowania_ogółem_kobiety_2003', 'zameldowania_ogółem_kobiety_2004', 'zameldowania_ogółem_kobiety_2005', 'zameldowania_ogółem_kobiety_2006', 'zameldowania_ogółem_kobiety_2007', 'zameldowania_ogółem_kobiety_2008', 'zameldowania_ogółem_kobiety_2009', 'zameldowania_ogółem_kobiety_2010', 'zameldowania_ogółem_kobiety_2011', 'zameldowania_ogółem_kobiety_2012', 'zameldowania_ogółem_kobiety_2013', 'zameldowania_ogółem_kobiety_2014', 'zameldowania_ogółem_kobiety_2015', 'zameldowania_ogółem_kobiety_2016', 'zameldowania_ogółem_kobiety_2017', 'zameldowania_ogółem_kobiety_2018', 'zameldowania_ogółem_kobiety_2019', 'zameldowania_ogółem_kobiety_2020', 'zameldowania_ogółem_kobiety_2021', 'zameldowania_ogółem_kobiety_2022', 'zameldowania_ogółem_kobiety_2023', 'zameldowania_ogółem_kobiety_2024', 'zameldowania_ogółem_kobiety_2025', 'zameldowania_z_miast_ogółem_1999', 'zameldowania_z_miast_ogółem_2000', 'zameldowania_z_miast_ogółem_2001', 'zameldowania_z_miast_ogółem_2002', 'zameldowania_z_miast_ogółem_2003', 'zameldowania_z_miast_ogółem_2004', 'zameldowania_z_miast_ogółem_2005', 'zameldowania_z_miast_ogółem_2006', 'zameldowania_z_miast_ogółem_2007', 'zameldowania_z_miast_ogółem_2008', 'zameldowania_z_miast_ogółem_2009', 'zameldowania_z_miast_ogółem_2010', 'zameldowania_z_miast_ogółem_2011', 'zameldowania_z_miast_ogółem_2012', 'zameldowania_z_miast_ogółem_2013', 'zameldowania_z_miast_ogółem_2014', 'zameldowania_z_miast_ogółem_2015', 'zameldowania_z_miast_ogółem_2016', 'zameldowania_z_miast_ogółem_2017', 'zameldowania_z_miast_ogółem_2018', 'zameldowania_z_miast_ogółem_2019', 'zameldowania_z_miast_ogółem_2020', 'zameldowania_z_miast_ogółem_2021', 'zameldowania_z_miast_ogółem_2022', 'zameldowania_z_miast_ogółem_2023', 'zameldowania_z_miast_ogółem_2024', 'zameldowania_z_miast_ogółem_2025', 'zameldowania_z_miast_mężczyźni_1999', 'zameldowania_z_miast_mężczyźni_2000', 'zameldowania_z_miast_mężczyźni_2001', 'zameldowania_z_miast_mężczyźni_2002', 'zameldowania_z_miast_mężczyźni_2003', 'zameldowania_z_miast_mężczyźni_2004', 'zameldowania_z_miast_mężczyźni_2005', 'zameldowania_z_miast_mężczyźni_2006', 'zameldowania_z_miast_mężczyźni_2007', 'zameldowania_z_miast_mężczyźni_2008', 'zameldowania_z_miast_mężczyźni_2009', 'zameldowania_z_miast_mężczyźni_2010', 'zameldowania_z_miast_mężczyźni_2011', 'zameldowania_z_miast_mężczyźni_2012', 'zameldowania_z_miast_mężczyźni_2013', 'zameldowania_z_miast_mężczyźni_2014', 'zameldowania_z_miast_mężczyźni_2015', 'zameldowania_z_miast_mężczyźni_2016', 'zameldowania_z_miast_mężczyźni_2017', 'zameldowania_z_miast_mężczyźni_2018', 'zameldowania_z_miast_mężczyźni_2019', 'zameldowania_z_miast_mężczyźni_2020', 'zameldowania_z_miast_mężczyźni_2021', 'zameldowania_z_miast_mężczyźni_2022', 'zameldowania_z_miast_mężczyźni_2023', 'zameldowania_z_miast_mężczyźni_2024', 'zameldowania_z_miast_mężczyźni_2025', 'zameldowania_z_miast_kobiety_1999', 'zameldowania_z_miast_kobiety_2000', 'zameldowania_z_miast_kobiety_2001', 'zameldowania_z_miast_kobiety_2002', 'zameldowania_z_miast_kobiety_2003', 'zameldowania_z_miast_kobiety_2004', 'zameldowania_z_miast_kobiety_2005', 'zameldowania_z_miast_kobiety_2006', 'zameldowania_z_miast_kobiety_2007', 'zameldowania_z_miast_kobiety_2008', 'zameldowania_z_miast_kobiety_2009', 'zameldowania_z_miast_kobiety_2010', 'zameldowania_z_miast_kobiety_2011', 'zameldowania_z_miast_kobiety_2012', 'zameldowania_z_miast_kobiety_2013', 'zameldowania_z_miast_kobiety_2014', 'zameldowania_z_miast_kobiety_2015', 'zameldowania_z_miast_kobiety_2016', 'zameldowania_z_miast_kobiety_2017', 'zameldowania_z_miast_kobiety_2018', 'zameldowania_z_miast_kobiety_2019', 'zameldowania_z_miast_kobiety_2020', 'zameldowania_z_miast_kobiety_2021', 'zameldowania_z_miast_kobiety_2022', 'zameldowania_z_miast_kobiety_2023', 'zameldowania_z_miast_kobiety_2024', 'zameldowania_z_miast_kobiety_2025', 'zameldowania_ze_wsi_ogółem_1999', 'zameldowania_ze_wsi_ogółem_2000', 'zameldowania_ze_wsi_ogółem_2001', 'zameldowania_ze_wsi_ogółem_2002', 'zameldowania_ze_wsi_ogółem_2003', 'zameldowania_ze_wsi_ogółem_2004', 'zameldowania_ze_wsi_ogółem_2005', 'zameldowania_ze_wsi_ogółem_2006', 'zameldowania_ze_wsi_ogółem_2007', 'zameldowania_ze_wsi_ogółem_2008', 'zameldowania_ze_wsi_ogółem_2009', 'zameldowania_ze_wsi_ogółem_2010', 'zameldowania_ze_wsi_ogółem_2011', 'zameldowania_ze_wsi_ogółem_2012', 'zameldowania_ze_wsi_ogółem_2013', 'zameldowania_ze_wsi_ogółem_2014', 'zameldowania_ze_wsi_ogółem_2015', 'zameldowania_ze_wsi_ogółem_2016', 'zameldowania_ze_wsi_ogółem_2017', 'zameldowania_ze_wsi_ogółem_2018', 'zameldowania_ze_wsi_ogółem_2019', 'zameldowania_ze_wsi_ogółem_2020', 'zameldowania_ze_wsi_ogółem_2021', 'zameldowania_ze_wsi_ogółem_2022', 'zameldowania_ze_wsi_ogółem_2023', 'zameldowania_ze_wsi_ogółem_2024', 'zameldowania_ze_wsi_ogółem_2025', 'zameldowania_ze_wsi_mężczyźni_1999', 'zameldowania_ze_wsi_mężczyźni_2000', 'zameldowania_ze_wsi_mężczyźni_2001', 'zameldowania_ze_wsi_mężczyźni_2002', 'zameldowania_ze_wsi_mężczyźni_2003', 'zameldowania_ze_wsi_mężczyźni_2004', 'zameldowania_ze_wsi_mężczyźni_2005', 'zameldowania_ze_wsi_mężczyźni_2006', 'zameldowania_ze_wsi_mężczyźni_2007', 'zameldowania_ze_wsi_mężczyźni_2008', 'zameldowania_ze_wsi_mężczyźni_2009', 'zameldowania_ze_wsi_mężczyźni_2010', 'zameldowania_ze_wsi_mężczyźni_2011', 'zameldowania_ze_wsi_mężczyźni_2012', 'zameldowania_ze_wsi_mężczyźni_2013', 'zameldowania_ze_wsi_mężczyźni_2014', 'zameldowania_ze_wsi_mężczyźni_2015', 'zameldowania_ze_wsi_mężczyźni_2016', 'zameldowania_ze_wsi_mężczyźni_2017', 'zameldowania_ze_wsi_mężczyźni_2018', 'zameldowania_ze_wsi_mężczyźni_2019', 'zameldowania_ze_wsi_mężczyźni_2020', 'zameldowania_ze_wsi_mężczyźni_2021', 'zameldowania_ze_wsi_mężczyźni_2022', 'zameldowania_ze_wsi_mężczyźni_2023', 'zameldowania_ze_wsi_mężczyźni_2024', 'zameldowania_ze_wsi_mężczyźni_2025', 'zameldowania_ze_wsi_kobiety_1999', 'zameldowania_ze_wsi_kobiety_2000', 'zameldowania_ze_wsi_kobiety_2001', 'zameldowania_ze_wsi_kobiety_2002', 'zameldowania_ze_wsi_kobiety_2003', 'zameldowania_ze_wsi_kobiety_2004', 'zameldowania_ze_wsi_kobiety_2005', 'zameldowania_ze_wsi_kobiety_2006', 'zameldowania_ze_wsi_kobiety_2007', 'zameldowania_ze_wsi_kobiety_2008', 'zameldowania_ze_wsi_kobiety_2009', 'zameldowania_ze_wsi_kobiety_2010', 'zameldowania_ze_wsi_kobiety_2011', 'zameldowania_ze_wsi_kobiety_2012', 'zameldowania_ze_wsi_kobiety_2013', 'zameldowania_ze_wsi_kobiety_2014', 'zameldowania_ze_wsi_kobiety_2015', 'zameldowania_ze_wsi_kobiety_2016', 'zameldowania_ze_wsi_kobiety_2017', 'zameldowania_ze_wsi_kobiety_2018', 'zameldowania_ze_wsi_kobiety_2019', 'zameldowania_ze_wsi_kobiety_2020', 'zameldowania_ze_wsi_kobiety_2021', 'zameldowania_ze_wsi_kobiety_2022', 'zameldowania_ze_wsi_kobiety_2023', 'zameldowania_ze_wsi_kobiety_2024', 'zameldowania_ze_wsi_kobiety_2025', 'wymeldowania_ogółem_ogółem_1999', 'wymeldowania_ogółem_ogółem_2000', 'wymeldowania_ogółem_ogółem_2001', 'wymeldowania_ogółem_ogółem_2002', 'wymeldowania_ogółem_ogółem_2003', 'wymeldowania_ogółem_ogółem_2004', 'wymeldowania_ogółem_ogółem_2005', 'wymeldowania_ogółem_ogółem_2006', 'wymeldowania_ogółem_ogółem_2007', 'wymeldowania_ogółem_ogółem_2008', 'wymeldowania_ogółem_ogółem_2009', 'wymeldowania_ogółem_ogółem_2010', 'wymeldowania_ogółem_ogółem_2011', 'wymeldowania_ogółem_ogółem_2012', 'wymeldowania_ogółem_ogółem_2013', 'wymeldowania_ogółem_ogółem_2014', 'wymeldowania_ogółem_ogółem_2015', 'wymeldowania_ogółem_ogółem_2016', 'wymeldowania_ogółem_ogółem_2017', 'wymeldowania_ogółem_ogółem_2018', 'wymeldowania_ogółem_ogółem_2019', 'wymeldowania_ogółem_ogółem_2020', 'wymeldowania_ogółem_ogółem_2021', 'wymeldowania_ogółem_ogółem_2022', 'wymeldowania_ogółem_ogółem_2023', 'wymeldowania_ogółem_ogółem_2024', 'wymeldowania_ogółem_ogółem_2025', 'wymeldowania_ogółem_mężczyźni_1999', 'wymeldowania_ogółem_mężczyźni_2000', 'wymeldowania_ogółem_mężczyźni_2001', 'wymeldowania_ogółem_mężczyźni_2002', 'wymeldowania_ogółem_mężczyźni_2003', 'wymeldowania_ogółem_mężczyźni_2004', 'wymeldowania_ogółem_mężczyźni_2005', 'wymeldowania_ogółem_mężczyźni_2006', 'wymeldowania_ogółem_mężczyźni_2007', 'wymeldowania_ogółem_mężczyźni_2008', 'wymeldowania_ogółem_mężczyźni_2009', 'wymeldowania_ogółem_mężczyźni_2010', 'wymeldowania_ogółem_mężczyźni_2011', 'wymeldowania_ogółem_mężczyźni_2012', 'wymeldowania_ogółem_mężczyźni_2013', 'wymeldowania_ogółem_mężczyźni_2014', 'wymeldowania_ogółem_mężczyźni_2015', 'wymeldowania_ogółem_mężczyźni_2016', 'wymeldowania_ogółem_mężczyźni_2017', 'wymeldowania_ogółem_mężczyźni_2018', 'wymeldowania_ogółem_mężczyźni_2019', 'wymeldowania_ogółem_mężczyźni_2020', 'wymeldowania_ogółem_mężczyźni_2021', 'wymeldowania_ogółem_mężczyźni_2022', 'wymeldowania_ogółem_mężczyźni_2023', 'wymeldowania_ogółem_mężczyźni_2024', 'wymeldowania_ogółem_mężczyźni_2025', 'wymeldowania_ogółem_kobiety_1999', 'wymeldowania_ogółem_kobiety_2000', 'wymeldowania_ogółem_kobiety_2001', 'wymeldowania_ogółem_kobiety_2002', 'wymeldowania_ogółem_kobiety_2003', 'wymeldowania_ogółem_kobiety_2004', 'wymeldowania_ogółem_kobiety_2005', 'wymeldowania_ogółem_kobiety_2006', 'wymeldowania_ogółem_kobiety_2007', 'wymeldowania_ogółem_kobiety_2008', 'wymeldowania_ogółem_kobiety_2009', 'wymeldowania_ogółem_kobiety_2010', 'wymeldowania_ogółem_kobiety_2011', 'wymeldowania_ogółem_kobiety_2012', 'wymeldowania_ogółem_kobiety_2013', 'wymeldowania_ogółem_kobiety_2014', 'wymeldowania_ogółem_kobiety_2015', 'wymeldowania_ogółem_kobiety_2016', 'wymeldowania_ogółem_kobiety_2017', 'wymeldowania_ogółem_kobiety_2018', 'wymeldowania_ogółem_kobiety_2019', 'wymeldowania_ogółem_kobiety_2020', 'wymeldowania_ogółem_kobiety_2021', 'wymeldowania_ogółem_kobiety_2022', 'wymeldowania_ogółem_kobiety_2023', 'wymeldowania_ogółem_kobiety_2024', 'wymeldowania_ogółem_kobiety_2025', 'wymeldowania_do_miast_ogółem_1999', 'wymeldowania_do_miast_ogółem_2000', 'wymeldowania_do_miast_ogółem_2001', 'wymeldowania_do_miast_ogółem_2002', 'wymeldowania_do_miast_ogółem_2003', 'wymeldowania_do_miast_ogółem_2004', 'wymeldowania_do_miast_ogółem_2005', 'wymeldowania_do_miast_ogółem_2006', 'wymeldowania_do_miast_ogółem_2007', 'wymeldowania_do_miast_ogółem_2008', 'wymeldowania_do_miast_ogółem_2009', 'wymeldowania_do_miast_ogółem_2010', 'wymeldowania_do_miast_ogółem_2011', 'wymeldowania_do_miast_ogółem_2012', 'wymeldowania_do_miast_ogółem_2013', 'wymeldowania_do_miast_ogółem_2014', 'wymeldowania_do_miast_ogółem_2015', 'wymeldowania_do_miast_ogółem_2016', 'wymeldowania_do_miast_ogółem_2017', 'wymeldowania_do_miast_ogółem_2018', 'wymeldowania_do_miast_ogółem_2019', 'wymeldowania_do_miast_ogółem_2020', 'wymeldowania_do_miast_ogółem_2021', 'wymeldowania_do_miast_ogółem_2022', 'wymeldowania_do_miast_ogółem_2023', 'wymeldowania_do_miast_ogółem_2024', 'wymeldowania_do_miast_ogółem_2025', 'wymeldowania_do_miast_mężczyźni_1999', 'wymeldowania_do_miast_mężczyźni_2000', 'wymeldowania_do_miast_mężczyźni_2001', 'wymeldowania_do_miast_mężczyźni_2002', 'wymeldowania_do_miast_mężczyźni_2003', 'wymeldowania_do_miast_mężczyźni_2004', 'wymeldowania_do_miast_mężczyźni_2005', 'wymeldowania_do_miast_mężczyźni_2006', 'wymeldowania_do_miast_mężczyźni_2007', 'wymeldowania_do_miast_mężczyźni_2008', 'wymeldowania_do_miast_mężczyźni_2009', 'wymeldowania_do_miast_mężczyźni_2010', 'wymeldowania_do_miast_mężczyźni_2011', 'wymeldowania_do_miast_mężczyźni_2012', 'wymeldowania_do_miast_mężczyźni_2013', 'wymeldowania_do_miast_mężczyźni_2014', 'wymeldowania_do_miast_mężczyźni_2015', 'wymeldowania_do_miast_mężczyźni_2016', 'wymeldowania_do_miast_mężczyźni_2017', 'wymeldowania_do_miast_mężczyźni_2018', 'wymeldowania_do_miast_mężczyźni_2019', 'wymeldowania_do_miast_mężczyźni_2020', 'wymeldowania_do_miast_mężczyźni_2021', 'wymeldowania_do_miast_mężczyźni_2022', 'wymeldowania_do_miast_mężczyźni_2023', 'wymeldowania_do_miast_mężczyźni_2024', 'wymeldowania_do_miast_mężczyźni_2025', 'wymeldowania_do_miast_kobiety_1999', 'wymeldowania_do_miast_kobiety_2000', 'wymeldowania_do_miast_kobiety_2001', 'wymeldowania_do_miast_kobiety_2002', 'wymeldowania_do_miast_kobiety_2003', 'wymeldowania_do_miast_kobiety_2004', 'wymeldowania_do_miast_kobiety_2005', 'wymeldowania_do_miast_kobiety_2006', 'wymeldowania_do_miast_kobiety_2007', 'wymeldowania_do_miast_kobiety_2008', 'wymeldowania_do_miast_kobiety_2009', 'wymeldowania_do_miast_kobiety_2010', 'wymeldowania_do_miast_kobiety_2011', 'wymeldowania_do_miast_kobiety_2012', 'wymeldowania_do_miast_kobiety_2013', 'wymeldowania_do_miast_kobiety_2014', 'wymeldowania_do_miast_kobiety_2015', 'wymeldowania_do_miast_kobiety_2016', 'wymeldowania_do_miast_kobiety_2017', 'wymeldowania_do_miast_kobiety_2018', 'wymeldowania_do_miast_kobiety_2019', 'wymeldowania_do_miast_kobiety_2020', 'wymeldowania_do_miast_kobiety_2021', 'wymeldowania_do_miast_kobiety_2022', 'wymeldowania_do_miast_kobiety_2023', 'wymeldowania_do_miast_kobiety_2024', 'wymeldowania_do_miast_kobiety_2025', 'wymeldowania_na_wieś_ogółem_1999', 'wymeldowania_na_wieś_ogółem_2000', 'wymeldowania_na_wieś_ogółem_2001', 'wymeldowania_na_wieś_ogółem_2002', 'wymeldowania_na_wieś_ogółem_2003', 'wymeldowania_na_wieś_ogółem_2004', 'wymeldowania_na_wieś_ogółem_2005', 'wymeldowania_na_wieś_ogółem_2006', 'wymeldowania_na_wieś_ogółem_2007', 'wymeldowania_na_wieś_ogółem_2008', 'wymeldowania_na_wieś_ogółem_2009', 'wymeldowania_na_wieś_ogółem_2010', 'wymeldowania_na_wieś_ogółem_2011', 'wymeldowania_na_wieś_ogółem_2012', 'wymeldowania_na_wieś_ogółem_2013', 'wymeldowania_na_wieś_ogółem_2014', 'wymeldowania_na_wieś_ogółem_2015', 'wymeldowania_na_wieś_ogółem_2016', 'wymeldowania_na_wieś_ogółem_2017', 'wymeldowania_na_wieś_ogółem_2018', 'wymeldowania_na_wieś_ogółem_2019', 'wymeldowania_na_wieś_ogółem_2020', 'wymeldowania_na_wieś_ogółem_2021', 'wymeldowania_na_wieś_ogółem_2022', 'wymeldowania_na_wieś_ogółem_2023', 'wymeldowania_na_wieś_ogółem_2024', 'wymeldowania_na_wieś_ogółem_2025', 'wymeldowania_na_wieś_mężczyźni_1999', 'wymeldowania_na_wieś_mężczyźni_2000', 'wymeldowania_na_wieś_mężczyźni_2001', 'wymeldowania_na_wieś_mężczyźni_2002', 'wymeldowania_na_wieś_mężczyźni_2003', 'wymeldowania_na_wieś_mężczyźni_2004', 'wymeldowania_na_wieś_mężczyźni_2005', 'wymeldowania_na_wieś_mężczyźni_2006', 'wymeldowania_na_wieś_mężczyźni_2007', 'wymeldowania_na_wieś_mężczyźni_2008', 'wymeldowania_na_wieś_mężczyźni_2009', 'wymeldowania_na_wieś_mężczyźni_2010', 'wymeldowania_na_wieś_mężczyźni_2011', 'wymeldowania_na_wieś_mężczyźni_2012', 'wymeldowania_na_wieś_mężczyźni_2013', 'wymeldowania_na_wieś_mężczyźni_2014', 'wymeldowania_na_wieś_mężczyźni_2015', 'wymeldowania_na_wieś_mężczyźni_2016', 'wymeldowania_na_wieś_mężczyźni_2017', 'wymeldowania_na_wieś_mężczyźni_2018', 'wymeldowania_na_wieś_mężczyźni_2019', 'wymeldowania_na_wieś_mężczyźni_2020', 'wymeldowania_na_wieś_mężczyźni_2021', 'wymeldowania_na_wieś_mężczyźni_2022', 'wymeldowania_na_wieś_mężczyźni_2023', 'wymeldowania_na_wieś_mężczyźni_2024', 'wymeldowania_na_wieś_mężczyźni_2025', 'wymeldowania_na_wieś_kobiety_1999', 'wymeldowania_na_wieś_kobiety_2000', 'wymeldowania_na_wieś_kobiety_2001', 'wymeldowania_na_wieś_kobiety_2002', 'wymeldowania_na_wieś_kobiety_2003', 'wymeldowania_na_wieś_kobiety_2004', 'wymeldowania_na_wieś_kobiety_2005', 'wymeldowania_na_wieś_kobiety_2006', 'wymeldowania_na_wieś_kobiety_2007', 'wymeldowania_na_wieś_kobiety_2008', 'wymeldowania_na_wieś_kobiety_2009', 'wymeldowania_na_wieś_kobiety_2010', 'wymeldowania_na_wieś_kobiety_2011', 'wymeldowania_na_wieś_kobiety_2012', 'wymeldowania_na_wieś_kobiety_2013', 'wymeldowania_na_wieś_kobiety_2014', 'wymeldowania_na_wieś_kobiety_2015', 'wymeldowania_na_wieś_kobiety_2016', 'wymeldowania_na_wieś_kobiety_2017', 'wymeldowania_na_wieś_kobiety_2018', 'wymeldowania_na_wieś_kobiety_2019', 'wymeldowania_na_wieś_kobiety_2020', 'wymeldowania_na_wieś_kobiety_2021', 'wymeldowania_na_wieś_kobiety_2022', 'wymeldowania_na_wieś_kobiety_2023', 'wymeldowania_na_wieś_kobiety_2024', 'wymeldowania_na_wieś_kobiety_2025', 'saldo_migracji_ogółem_1999', 'saldo_migracji_ogółem_2000', 'saldo_migracji_ogółem_2001', 'saldo_migracji_ogółem_2002', 'saldo_migracji_ogółem_2003', 'saldo_migracji_ogółem_2004', 'saldo_migracji_ogółem_2005', 'saldo_migracji_ogółem_2006', 'saldo_migracji_ogółem_2007', 'saldo_migracji_ogółem_2008', 'saldo_migracji_ogółem_2009', 'saldo_migracji_ogółem_2010', 'saldo_migracji_ogółem_2011', 'saldo_migracji_ogółem_2012', 'saldo_migracji_ogółem_2013', 'saldo_migracji_ogółem_2014', 'saldo_migracji_ogółem_2015', 'saldo_migracji_ogółem_2016', 'saldo_migracji_ogółem_2017', 'saldo_migracji_ogółem_2018', 'saldo_migracji_ogółem_2019', 'saldo_migracji_ogółem_2020', 'saldo_migracji_ogółem_2021', 'saldo_migracji_ogółem_2022', 'saldo_migracji_ogółem_2023', 'saldo_migracji_ogółem_2024', 'saldo_migracji_ogółem_2025', 'saldo_migracji_mężczyźni_1999', 'saldo_migracji_mężczyźni_2000', 'saldo_migracji_mężczyźni_2001', 'saldo_migracji_mężczyźni_2002', 'saldo_migracji_mężczyźni_2003', 'saldo_migracji_mężczyźni_2004', 'saldo_migracji_mężczyźni_2005', 'saldo_migracji_mężczyźni_2006', 'saldo_migracji_mężczyźni_2007', 'saldo_migracji_mężczyźni_2008', 'saldo_migracji_mężczyźni_2009', 'saldo_migracji_mężczyźni_2010', 'saldo_migracji_mężczyźni_2011', 'saldo_migracji_mężczyźni_2012', 'saldo_migracji_mężczyźni_2013', 'saldo_migracji_mężczyźni_2014', 'saldo_migracji_mężczyźni_2015', 'saldo_migracji_mężczyźni_2016', 'saldo_migracji_mężczyźni_2017', 'saldo_migracji_mężczyźni_2018', 'saldo_migracji_mężczyźni_2019', 'saldo_migracji_mężczyźni_2020', 'saldo_migracji_mężczyźni_2021', 'saldo_migracji_mężczyźni_2022', 'saldo_migracji_mężczyźni_2023', 'saldo_migracji_mężczyźni_2024', 'saldo_migracji_mężczyźni_2025', 'saldo_migracji_kobiety_1999', 'saldo_migracji_kobiety_2000', 'saldo_migracji_kobiety_2001', 'saldo_migracji_kobiety_2002', 'saldo_migracji_kobiety_2003', 'saldo_migracji_kobiety_2004', 'saldo_migracji_kobiety_2005', 'saldo_migracji_kobiety_2006', 'saldo_migracji_kobiety_2007', 'saldo_migracji_kobiety_200

In [9]:
df_long = df.melt(
    id_vars="region",
    var_name="zmienna",
    value_name="wartosc"
)
display(df_long.head())

               region                          zmienna wartosc
0              POLSKA  zameldowania_ogółem_ogółem_1999  311080
1        DOLNOŚLĄSKIE  zameldowania_ogółem_ogółem_1999   23789
2  KUJAWSKO-POMORSKIE  zameldowania_ogółem_ogółem_1999   18407
3           LUBELSKIE  zameldowania_ogółem_ogółem_1999   18316
4            LUBUSKIE  zameldowania_ogółem_ogółem_1999    8705

In [10]:
df_long[["typ", "rok"]] = df_long["zmienna"].str.rsplit("_", n=1, expand=True)
df_long["rok"] = df_long["rok"].astype(int)

display(df_long.head())

,region,zmienna,wartosc,typ,rok
0,POLSKA,zameldowania_ogółem_ogółem_1999,311080,zameldowania_ogółem_ogółem,1999
1,DOLNOŚLĄSKIE,zameldowania_ogółem_ogółem_1999,23789,zameldowania_ogółem_ogółem,1999
2,KUJAWSKO-POMORSKIE,zameldowania_ogółem_ogółem_1999,18407,zameldowania_ogółem_ogółem,1999
3,LUBELSKIE,zameldowania_ogółem_ogółem_1999,18316,zameldowania_ogółem_ogółem,1999
4,LUBUSKIE,zameldowania_ogółem_ogółem_1999,8705,zameldowania_ogółem_ogółem,1999

In [11]:
df_final = df_long.pivot(
    index=["region", "rok"],
    columns="typ",
    values="wartosc"
).reset_index()

In [12]:
df_final = df_final.replace("-", np.nan)

C:\Users\user\AppData\Local\Temp\ipykernel_20588\1456364069.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_final = df_final.replace("-", np.nan)

In [13]:
display(df_final)

typ,region,rok,saldo_migracji_kobiety,saldo_migracji_mężczyźni,saldo_migracji_ogółem,wymeldowania_do_miast_kobiety,wymeldowania_do_miast_mężczyźni,wymeldowania_do_miast_ogółem,wymeldowania_na_wieś_kobiety,wymeldowania_na_wieś_mężczyźni,...,wymeldowania_ogółem_ogółem,zameldowania_ogółem_kobiety,zameldowania_ogółem_mężczyźni,zameldowania_ogółem_ogółem,zameldowania_z_miast_kobiety,zameldowania_z_miast_mężczyźni,zameldowania_z_miast_ogółem,zameldowania_ze_wsi_kobiety,zameldowania_ze_wsi_mężczyźni,zameldowania_ze_wsi_ogółem
0,DOLNOŚLĄSKIE,1999,-108.0,-175.0,-283.0,NaN,NaN,NaN,NaN,NaN,...,24072.0,12397.0,11392.0,23789.0,NaN,NaN,NaN,NaN,NaN,NaN
1,DOLNOŚLĄSKIE,2000,-322.0,-251.0,-573.0,6897.0,6059.0,12956.0,3908.0,3796.0,...,20660.0,10483.0,9604.0,20087.0,7059.0,6544.0,13603.0,3424.0,3060.0,6484.0
2,DOLNOŚLĄSKIE,2001,52.0,125.0,177.0,6799.0,5994.0,12793.0,3771.0,3644.0,...,20208.0,10622.0,9763.0,20385.0,7355.0,6771.0,14126.0,3267.0,2992.0,6259.0
3,DOLNOŚLĄSKIE,2002,-321.0,-363.0,-684.0,7280.0,6292.0,13572.0,4116.0,4084.0,...,21772.0,11075.0,10013.0,21088.0,7802.0,7141.0,14943.0,3273.0,2872.0,6145.0
4,DOLNOŚLĄSKIE,2003,-743.0,-476.0,-1219.0,6986.0,5987.0,12973.0,4316.0,3923.0,...,21212.0,10559.0,9434.0,19993.0,7544.0,6788.0,14332.0,3015.0,2646.0,5661.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454,ŚWIĘTOKRZYSKIE,2021,-1281.0,-1140.0,-2421.0,3032.0,2581.0,5613.0,1883.0,1816.0,...,9312.0,3634.0,3257.0,6891.0,2051.0,1851.0,3902.0,1583.0,1406.0,2989.0
455,ŚWIĘTOKRZYSKIE,2022,-1324.0,-946.0,-2270.0,2925.0,2286.0,5211.0,1978.0,1830.0,...,9019.0,3579.0,3170.0,6749.0,1963.0,1848.0,3811.0,1616.0,1322.0,2938.0
456,ŚWIĘTOKRZYSKIE,2023,-1553.0,-1213.0,-2766.0,2883.0,2525.0,5408.0,1907.0,1798.0,...,9113.0,3237.0,3110.0,6347.0,1809.0,1843.0,3652.0,1428.0,1267.0,2695.0
457,ŚWIĘTOKRZYSKIE,2024,-1494.0,-1261.0,-2755.0,3070.0,2606.0,5676.0,2025.0,1927.0,...,9628.0,3601.0,3272.0,6873.0,1991.0,1902.0,3893.0,1610.0,1370.0,2980.0
458,ŚWIĘTOKRZYSKIE,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df_filtered = df_final.loc[:, df_final.columns.str.contains(r'^region$|^rok$|ogółem', regex=True)]

In [16]:
display(df_filtered)

typ,region,rok,saldo_migracji_ogółem,wymeldowania_do_miast_ogółem,wymeldowania_na_wieś_ogółem,wymeldowania_ogółem_kobiety,wymeldowania_ogółem_mężczyźni,wymeldowania_ogółem_ogółem,zameldowania_ogółem_kobiety,zameldowania_ogółem_mężczyźni,zameldowania_ogółem_ogółem,zameldowania_z_miast_ogółem,zameldowania_ze_wsi_ogółem
0,DOLNOŚLĄSKIE,1999,-283.0,NaN,NaN,12505.0,11567.0,24072.0,12397.0,11392.0,23789.0,NaN,NaN
1,DOLNOŚLĄSKIE,2000,-573.0,12956.0,7704.0,10805.0,9855.0,20660.0,10483.0,9604.0,20087.0,13603.0,6484.0
2,DOLNOŚLĄSKIE,2001,177.0,12793.0,7415.0,10570.0,9638.0,20208.0,10622.0,9763.0,20385.0,14126.0,6259.0
3,DOLNOŚLĄSKIE,2002,-684.0,13572.0,8200.0,11396.0,10376.0,21772.0,11075.0,10013.0,21088.0,14943.0,6145.0
4,DOLNOŚLĄSKIE,2003,-1219.0,12973.0,8239.0,11302.0,9910.0,21212.0,10559.0,9434.0,19993.0,14332.0,5661.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
454,ŚWIĘTOKRZYSKIE,2021,-2421.0,5613.0,3699.0,4915.0,4397.0,9312.0,3634.0,3257.0,6891.0,3902.0,2989.0
455,ŚWIĘTOKRZYSKIE,2022,-2270.0,5211.0,3808.0,4903.0,4116.0,9019.0,3579.0,3170.0,6749.0,3811.0,2938.0
456,ŚWIĘTOKRZYSKIE,2023,-2766.0,5408.0,3705.0,4790.0,4323.0,9113.0,3237.0,3110.0,6347.0,3652.0,2695.0
457,ŚWIĘTOKRZYSKIE,2024,-2755.0,5676.0,3952.0,5095.0,4533.0,9628.0,3601.0,3272.0,6873.0,3893.0,2980.0
458,ŚWIĘTOKRZYSKIE,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df_filtered.to_csv("data/processed/ludnosc.csv", index=False)

In [18]:
df_filtered.describe()

typ,rok,saldo_migracji_ogółem,wymeldowania_do_miast_ogółem,wymeldowania_na_wieś_ogółem,wymeldowania_ogółem_kobiety,wymeldowania_ogółem_mężczyźni,wymeldowania_ogółem_ogółem,zameldowania_ogółem_kobiety,zameldowania_ogółem_mężczyźni,zameldowania_ogółem_ogółem,zameldowania_z_miast_ogółem,zameldowania_ze_wsi_ogółem
count,459.000000,442.000000,425.000000,425.000000,442.000000,442.000000,442.000000,442.000000,442.000000,442.000000,425.000000,425.000000
mean,2012.000000,0.000000,20965.350588,14551.552941,18910.307692,16648.162896,35558.470588,18910.307692,16648.162896,35558.470588,23748.009412,11768.894118
std,7.797379,3806.951406,39957.536044,27725.167097,35954.818608,31673.705158,67621.909719,36184.521738,31840.862626,68018.477858,45628.568850,22424.892698
min,1999.000000,-6495.000000,3397.000000,2445.000000,3165.000000,2849.000000,6038.000000,2779.000000,2431.000000,5228.000000,2977.000000,2088.000000
25%,2005.000000,-2167.500000,7709.000000,4592.000000,6708.000000,5667.250000,12457.000000,5415.500000,4713.250000,10201.750000,6043.000000,4052.000000
50%,2012.000000,-944.500000,10056.000000,7409.000000,9431.000000,8239.500000,17732.500000,8211.500000,7358.000000,15552.000000,9907.000000,5839.000000
75%,2019.000000,1382.500000,12973.000000,11112.000000,12501.000000,11274.000000,23663.750000,13855.000000,12297.750000,26132.000000,17669.000000,7814.000000
max,2025.000000,16268.000000,209034.000000,151851.000000,191385.000000,169500.000000,360885.000000,191385.000000,169500.000000,360885.000000,243957.000000,118987.000000

In [19]:
df_filtered.missing_values = df_filtered.isnull().sum()
display(df_filtered.missing_values)

C:\Users\user\AppData\Local\Temp\ipykernel_20588\1374523962.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_filtered.missing_values = df_filtered.isnull().sum()

typ
region                            0
rok                               0
saldo_migracji_ogółem            17
wymeldowania_do_miast_ogółem     34
wymeldowania_na_wieś_ogółem      34
wymeldowania_ogółem_kobiety      17
wymeldowania_ogółem_mężczyźni    17
wymeldowania_ogółem_ogółem       17
zameldowania_ogółem_kobiety      17
zameldowania_ogółem_mężczyźni    17
zameldowania_ogółem_ogółem       17
zameldowania_z_miast_ogółem      34
zameldowania_ze_wsi_ogółem       34
dtype: int64