In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
df_wynagrodzenia = pd.read_csv('data/processed/wynagrodzenia.csv')
df_wolne_miejsca_pracy = pd.read_csv('data/processed/wolne_miejsca_pracy.csv')
df_szkolnictwo = pd.read_csv('data/processed/szkolnictwo.csv')
df_odsetek_produkcyjny = pd.read_csv('data/processed/odsetek_produkcyjny.csv')
df_ludnosci = pd.read_csv('data/processed/ludnosc.csv')
df_liczba_podmiotow_gospodarczych = pd.read_csv('data/processed/liczba_podmiotow_gospodarczych.csv')
df_inwestycje = pd.read_csv('data/processed/inwestycje.csv')
df_absolwenci = pd.read_csv('data/processed/absolwenci.csv')

df_meszkania = pd.read_excel('data/processed/power_query/mieszkania-oddane-do-użytkowania-na-10-tys.-ludności.xlsx', sheet_name='mieszkania oddane_ długi układ')
df_podmiot_z_udzialem_kap_zagranicznego = pd.read_excel('data/processed/power_query/tabela-układ-długi-danych.xlsx', sheet_name='podm. z udz. kap. zagraniczn.')
df_podmiot_nowo_zarejestr = pd.read_excel('data/processed/power_query/tabela-układ-długi-danych.xlsx', sheet_name='podm. nowo zarejestr.')

In [12]:
df_meszkania = df_meszkania.rename(columns={'Rok': 'rok', 'Region': 'region', 'Mieszkania oddane do użytkowania na 10 tys. ludności': 'mieszkania_oddane_do_uzytkowania_na_10_tys_ludnosci'})
df_meszkania = df_meszkania.iloc[:, 1:]
display(df_meszkania.head())

   region   rok  mieszkania oddane do użytkowania na 10 tys. ludności
0  POLSKA  2002                                               25.5
1  POLSKA  2003                                               42.6
2  POLSKA  2004                                               28.3
3  POLSKA  2005                                               29.9
4  POLSKA  2006                                               30.3

In [ ]:
df_podmiot_z_udzialem_kap_zagranicznego = df_podmiot_z_udzialem_kap_zagranicznego.rename(columns={'Rok': 'rok', 'Jednosta terytorialna': 'region', 'podmioty z udziałem kapitału zagranicznego na 10 tys. mieszkańców': 'podmiot_z_udzialem_kap_zagranicznego_na_10_tys_mieszkancow'})
df_podmiot_z_udzialem_kap_zagranicznego = df_podmiot_z_udzialem_kap_zagranicznego.iloc[:, 1:]


display(df_podmiot_z_udzialem_kap_zagranicznego.head())

   region   rok  podmiot_z_udzialem_kap_zagranicznego_na_10_tys_mieszkancow
0  POLSKA  2003                                                4.0
1  POLSKA  2004                                                4.1
2  POLSKA  2005                                                4.4
3  POLSKA  2006                                                4.7
4  POLSKA  2007                                                4.9

In [17]:
df_podmiot_nowo_zarejestr = df_podmiot_nowo_zarejestr.rename(columns={'Rok': 'rok', 'podmioty nowo zarejestrowane na 10 tys. ludności w wieku produkcyjnym': 'podmiot_nowo_zarejestr_na_10_tys_ludnosci_w_wieku_produkcyjnym'})
df_podmiot_nowo_zarejestr = df_podmiot_nowo_zarejestr.iloc[:, 1:]

display(df_podmiot_nowo_zarejestr.head())

   region   rok podmiot_nowo_zarejestr_na_10_tys_ludnosci_w_wieku_produkcyjnym
0  POLSKA  2002                                                  -
1  POLSKA  2003                                                105
2  POLSKA  2004                                                 96
3  POLSKA  2005                                                107
4  POLSKA  2006                                                121

In [18]:
from functools import reduce

dfs = [
    df_wynagrodzenia,
    df_wolne_miejsca_pracy,
    df_szkolnictwo,
    df_odsetek_produkcyjny,
    df_ludnosci,
    df_liczba_podmiotow_gospodarczych,
    df_inwestycje,
    df_absolwenci,
    df_podmiot_z_udzialem_kap_zagranicznego,
    df_meszkania,
    df_podmiot_nowo_zarejestr
]

df_merged = reduce(
    lambda left, right: pd.merge(left, right, on=['region', 'rok'], how='outer'),
    dfs
)

In [19]:
df_merged

,region,wynagrodzenie,rok,bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym,ogółem,wartosc,typ_uczelni_x,"gimnazjalne,_podstawowe_i_niższe_ogółem_wartość_liczbowa","gimnazjalne,_podstawowe_i_niższe_ogółem_wskaźnik_precyzji",policealne_oraz_średnie_zawodowe/branżowe_ogółem_wartość_liczbowa,...,zameldowania_z_miast_ogółem,zameldowania_ze_wsi_ogółem,liczba_pomiotow_gospodarczych,inwestycje_zl,typ_inwestycji,absolwenci,typ_uczelni_y,podmiot_z_udzialem_kap_zagranicznego_na_10_tys_mieszkancow,mieszkania oddane do użytkowania na 10 tys. ludności,podmiot_nowo_zarejestr_na_10_tys_ludnosci_w_wieku_produkcyjnym
0,DOLNOŚLĄSKIE,NaN,1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DOLNOŚLĄSKIE,NaN,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13603.0,6484.0,NaN,3492.0,ogółem,NaN,NaN,NaN,NaN,NaN
2,DOLNOŚLĄSKIE,NaN,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14126.0,6259.0,NaN,3786.0,ogółem,NaN,NaN,NaN,NaN,NaN
3,DOLNOŚLĄSKIE,NaN,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14943.0,6145.0,"1593,7",3293.0,ogółem,NaN,NaN,NaN,24.5,-
4,DOLNOŚLĄSKIE,NaN,2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14332.0,5661.0,"1635,9",3129.0,ogółem,NaN,NaN,5.8,36.4,114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,ŚWIĘTOKRZYSKIE,"7664,18",2024,1.9,12511.0,3465.0,uczelnie publiczne,13.2,4.15,25.3,...,3893.0,2980.0,"2002,1",7967.0,ogółem,3465.0,uczelnie publiczne,2.1,40.9,134
983,ŚWIĘTOKRZYSKIE,"7664,18",2024,1.9,12511.0,3465.0,uczelnie publiczne,13.2,4.15,25.3,...,3893.0,2980.0,"2002,1",7967.0,ogółem,1378.0,uczelnie niepubliczne,2.1,40.9,134
984,ŚWIĘTOKRZYSKIE,"7664,18",2024,1.9,12511.0,1378.0,uczelnie niepubliczne,13.2,4.15,25.3,...,3893.0,2980.0,"2002,1",7967.0,ogółem,3465.0,uczelnie publiczne,2.1,40.9,134
985,ŚWIĘTOKRZYSKIE,"7664,18",2024,1.9,12511.0,1378.0,uczelnie niepubliczne,13.2,4.15,25.3,...,3893.0,2980.0,"2002,1",7967.0,ogółem,1378.0,uczelnie niepubliczne,2.1,40.9,134
986,ŚWIĘTOKRZYSKIE,NaN,2025,NaN,13782.0,NaN,NaN,-,-,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.8,NaN

In [22]:
df_merged.to_csv('data/processed/merged_data.csv', index=False)

In [20]:
df_merged.describe()

,rok,bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym,ogółem,wartosc,saldo_migracji_ogółem,wymeldowania_do_miast_ogółem,wymeldowania_na_wieś_ogółem,wymeldowania_ogółem_kobiety,wymeldowania_ogółem_mężczyźni,wymeldowania_ogółem_ogółem,zameldowania_ogółem_kobiety,zameldowania_ogółem_mężczyźni,zameldowania_ogółem_ogółem,zameldowania_z_miast_ogółem,zameldowania_ze_wsi_ogółem,inwestycje_zl,absolwenci,podmiot_z_udzialem_kap_zagranicznego_na_10_tys_mieszkancow,mieszkania oddane do użytkowania na 10 tys. ludności
count,987.000000,715.000000,8.680000e+02,640.000000,970.000000,953.000000,953.000000,970.000000,970.000000,970.000000,970.000000,970.000000,970.000000,953.000000,953.000000,928.000000,640.000000,902.000000,936.000000
mean,2015.744681,2.007972,4.193351e+04,10167.915625,0.000000,15337.068206,10862.090241,14010.453608,12370.946392,26381.400000,14010.453608,12370.946392,26381.400000,17402.554040,8796.604407,6983.960129,10167.915625,5.050998,44.344551
std,6.767484,0.831526,8.638591e+04,9746.695270,3947.843855,27514.353263,19042.100247,24957.644022,21991.467755,46944.036328,25300.467058,22252.024009,47547.314611,31700.715329,15446.399934,3020.758579,9746.695270,3.837014,16.757632
min,1999.000000,0.600000,4.199000e+03,97.000000,-6495.000000,3397.000000,2445.000000,3165.000000,2849.000000,6038.000000,2779.000000,2431.000000,5228.000000,2977.000000,2088.000000,1572.000000,97.000000,0.700000,11.000000
25%,2013.000000,1.400000,1.650825e+04,3702.750000,-2269.500000,7458.000000,4569.000000,6438.750000,5484.000000,11898.250000,5190.000000,4572.000000,9756.750000,5838.000000,3861.000000,5075.000000,3702.750000,2.400000,31.650000
50%,2017.000000,1.900000,2.563850e+04,6632.000000,-1034.000000,9743.000000,7325.000000,9166.000000,8053.500000,17278.000000,7888.500000,6964.000000,14872.000000,9374.000000,5812.000000,6614.000000,6632.000000,4.400000,41.450000
75%,2021.000000,2.500000,3.926700e+04,12667.500000,1544.250000,12292.000000,10635.000000,12065.000000,10740.250000,22929.000000,13729.250000,12194.000000,25947.250000,16873.000000,7794.000000,8485.000000,12667.500000,6.100000,55.475000
max,2025.000000,4.600000,1.139446e+06,48316.000000,16268.000000,209034.000000,151851.000000,191385.000000,169500.000000,360885.000000,191385.000000,169500.000000,360885.000000,243957.000000,118987.000000,20911.000000,48316.000000,21.100000,92.300000

In [21]:
df_merged.missing_values = df_merged.isnull().sum()
display(df_merged.missing_values)

C:\Users\user\AppData\Local\Temp\ipykernel_7836\2790110925.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_merged.missing_values = df_merged.isnull().sum()

region                                                                                            0
wynagrodzenie                                                                                   283
rok                                                                                               0
bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym                                              272
ogółem                                                                                          119
wartosc                                                                                         347
typ_uczelni_x                                                                                   283
gimnazjalne,_podstawowe_i_niższe_ogółem_wartość_liczbowa                                        187
gimnazjalne,_podstawowe_i_niższe_ogółem_wskaźnik_precyzji                                       187
policealne_oraz_średnie_zawodowe/branżowe_ogółem_wartość_liczbowa                               187
policealne_oraz_średnie_zawodowe/branżowe_ogółem_wskaźnik_precyzji                              187
wyższe_ogółem_wartość_liczbowa                                                                  187
wyższe_ogółem_wskaźnik_precyzji                                                                 187
zasadnicze_zawodowe/branżowe_ogółem_wartość_liczbowa                                            187
zasadnicze_zawodowe/branżowe_ogółem_wskaźnik_precyzji                                           187
średnie_(łącznie_z_zasadniczym_zawodowym/branżowym_i_policealnym)_ogółem_wartość_liczbowa       187
średnie_(łącznie_ze_średnim_zawodowym/branżowym_i_ogólnokształcącym)_ogółem_wartość_liczbowa    187
średnie_ogólnokształcące_ogółem_wartość_liczbowa                                                187
średnie_ogólnokształcące_ogółem_wskaźnik_precyzji                                               187
średnie_zawodowe/branżowe_ogółem_wartość_liczbowa                                               187
średnie_zawodowe/branżowe_ogółem_wskaźnik_precyzji                                              187
saldo_migracji_ogółem                                                                            17
wymeldowania_do_miast_ogółem                                                                     34
wymeldowania_na_wieś_ogółem                                                                      34
wymeldowania_ogółem_kobiety                                                                      17
wymeldowania_ogółem_mężczyźni                                                                    17
wymeldowania_ogółem_ogółem                                                                       17
zameldowania_ogółem_kobiety                                                                      17
zameldowania_ogółem_mężczyźni                                                                    17
zameldowania_ogółem_ogółem                                                                       17
zameldowania_z_miast_ogółem                                                                      34
zameldowania_ze_wsi_ogółem                                                                       34
liczba_pomiotow_gospodarczych                                                                    91
inwestycje_zl                                                                                    59
typ_inwestycji                                                                                   59
absolwenci                                                                                      347
typ_uczelni_y                                                                                   283
podmiot_z_udzialem_kap_zagranicznego_na_10_tys_mieszkancow                                       85
mieszkania oddane do użytkowania na 10 tys. ludności                                             51
podmiot_nowo_zarejestr_na_10_tys_ludnosci_w_wieku_produkcyjnym                                   68
dtype: int64