In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
df_wynagrodzenia = pd.read_csv('data/processed/wynagrodzenia.csv')
df_wolne_miejsca_pracy = pd.read_csv('data/processed/wolne_miejsca_pracy.csv')
df_odsetek_produkcyjny = pd.read_csv('data/processed/odsetek_produkcyjny.csv')
df_ludnosci = pd.read_csv('data/processed/ludnosc.csv')
df_liczba_podmiotow_gospodarczych = pd.read_csv('data/processed/liczba_podmiotow_gospodarczych.csv')
df_inwestycje = pd.read_csv('data/processed/inwestycje.csv')
df_absolwenci = pd.read_csv('data/processed/absolwenci.csv')

df_meszkania = pd.read_excel('data/processed/power_query/mieszkania-oddane-do-użytkowania-na-10-tys.-ludności.xlsx', sheet_name='mieszkania oddane_ długi układ')
df_podmiot_z_udzialem_kap_zagranicznego = pd.read_excel('data/processed/power_query/tabela-układ-długi-danych.xlsx', sheet_name='podm. z udz. kap. zagraniczn.')
df_podmiot_nowo_zarejestr = pd.read_excel('data/processed/power_query/tabela-układ-długi-danych.xlsx', sheet_name='podm. nowo zarejestr.')

In [14]:
df_meszkania = df_meszkania.rename(columns={'Rok': 'rok', 'Region': 'region', 'Mieszkania oddane do użytkowania na 10 tys. ludności': 'mieszkania_oddane_do_uzytkowania_na_10_tys_ludnosci'})
df_meszkania = df_meszkania.iloc[:, 1:]
display(df_meszkania.head())

   region   rok  mieszkania oddane do użytkowania na 10 tys. ludności
0  POLSKA  2002                                               25.5
1  POLSKA  2003                                               42.6
2  POLSKA  2004                                               28.3
3  POLSKA  2005                                               29.9
4  POLSKA  2006                                               30.3

In [15]:
df_podmiot_z_udzialem_kap_zagranicznego = df_podmiot_z_udzialem_kap_zagranicznego.rename(columns={'Rok': 'rok', 'Jednosta terytorialna': 'region', 'podmioty z udziałem kapitału zagranicznego na 10 tys. mieszkańców': 'podmiot_z_udzialem_kap_zagranicznego_na_10_tys_mieszkancow'})
df_podmiot_z_udzialem_kap_zagranicznego = df_podmiot_z_udzialem_kap_zagranicznego.iloc[:, 1:]


display(df_podmiot_z_udzialem_kap_zagranicznego.head())

   region   rok  podmiot_z_udzialem_kap_zagranicznego_na_10_tys_mieszkancow
0  POLSKA  2003                                                4.0
1  POLSKA  2004                                                4.1
2  POLSKA  2005                                                4.4
3  POLSKA  2006                                                4.7
4  POLSKA  2007                                                4.9

In [16]:
df_podmiot_nowo_zarejestr = df_podmiot_nowo_zarejestr.rename(columns={'Rok': 'rok', 'podmioty nowo zarejestrowane na 10 tys. ludności w wieku produkcyjnym': 'podmiot_nowo_zarejestr_na_10_tys_ludnosci_w_wieku_produkcyjnym'})
df_podmiot_nowo_zarejestr = df_podmiot_nowo_zarejestr.iloc[:, 1:]

display(df_podmiot_nowo_zarejestr.head())

   region   rok podmiot_nowo_zarejestr_na_10_tys_ludnosci_w_wieku_produkcyjnym
0  POLSKA  2002                                                  -
1  POLSKA  2003                                                105
2  POLSKA  2004                                                 96
3  POLSKA  2005                                                107
4  POLSKA  2006                                                121

In [17]:
from functools import reduce

dfs = [
    df_wynagrodzenia,
    df_wolne_miejsca_pracy,
    df_odsetek_produkcyjny,
    df_ludnosci,
    df_liczba_podmiotow_gospodarczych,
    df_inwestycje,
    df_absolwenci,
    df_podmiot_z_udzialem_kap_zagranicznego,
    df_meszkania,
    df_podmiot_nowo_zarejestr
]

df_merged = reduce(
    lambda left, right: pd.merge(left, right, on=['region', 'rok'], how='outer'),
    dfs
)

In [18]:
df_merged.columns.tolist()

['region',
 'wynagrodzenie',
 'rok',
 'bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym',
 'ogółem',
 'gimnazjalne,_podstawowe_i_niższe_ogółem_wartość_liczbowa',
 'gimnazjalne,_podstawowe_i_niższe_ogółem_wskaźnik_precyzji',
 'policealne_oraz_średnie_zawodowe/branżowe_ogółem_wartość_liczbowa',
 'policealne_oraz_średnie_zawodowe/branżowe_ogółem_wskaźnik_precyzji',
 'wyższe_ogółem_wartość_liczbowa',
 'wyższe_ogółem_wskaźnik_precyzji',
 'zasadnicze_zawodowe/branżowe_ogółem_wartość_liczbowa',
 'zasadnicze_zawodowe/branżowe_ogółem_wskaźnik_precyzji',
 'średnie_(łącznie_z_zasadniczym_zawodowym/branżowym_i_policealnym)_ogółem_wartość_liczbowa',
 'średnie_(łącznie_ze_średnim_zawodowym/branżowym_i_ogólnokształcącym)_ogółem_wartość_liczbowa',
 'średnie_ogólnokształcące_ogółem_wartość_liczbowa',
 'średnie_ogólnokształcące_ogółem_wskaźnik_precyzji',
 'średnie_zawodowe/branżowe_ogółem_wartość_liczbowa',
 'średnie_zawodowe/branżowe_ogółem_wskaźnik_precyzji',
 'saldo_migracji_ogółem',
 'wymeldowania_do_miast_ogółem',
 'wymeldowania_na_wieś_ogółem',
 'wymeldowania_ogółem_kobiety',
 'wymeldowania_ogółem_mężczyźni',
 'wymeldowania_ogółem_ogółem',
 'zameldowania_ogółem_kobiety',
 'zameldowania_ogółem_mężczyźni',
 'zameldowania_ogółem_ogółem',
 'zameldowania_z_miast_ogółem',
 'zameldowania_ze_wsi_ogółem',
 'liczba_pomiotow_gospodarczych',
 'inwestycje_zl',
 'typ_inwestycji',
 'uczelnie niepubliczne',
 'uczelnie publiczne',
 'podmiot_z_udzialem_kap_zagranicznego_na_10_tys_mieszkancow',
 'mieszkania oddane do użytkowania na 10 tys. ludności',
 'podmiot_nowo_zarejestr_na_10_tys_ludnosci_w_wieku_produkcyjnym']

In [19]:
df_merged

,region,wynagrodzenie,rok,bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym,ogółem,"gimnazjalne,_podstawowe_i_niższe_ogółem_wartość_liczbowa","gimnazjalne,_podstawowe_i_niższe_ogółem_wskaźnik_precyzji",policealne_oraz_średnie_zawodowe/branżowe_ogółem_wartość_liczbowa,policealne_oraz_średnie_zawodowe/branżowe_ogółem_wskaźnik_precyzji,wyższe_ogółem_wartość_liczbowa,...,zameldowania_z_miast_ogółem,zameldowania_ze_wsi_ogółem,liczba_pomiotow_gospodarczych,inwestycje_zl,typ_inwestycji,uczelnie niepubliczne,uczelnie publiczne,podmiot_z_udzialem_kap_zagranicznego_na_10_tys_mieszkancow,mieszkania oddane do użytkowania na 10 tys. ludności,podmiot_nowo_zarejestr_na_10_tys_ludnosci_w_wieku_produkcyjnym
0,DOLNOŚLĄSKIE,NaN,1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DOLNOŚLĄSKIE,NaN,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13603.0,6484.0,NaN,3492.0,ogółem,NaN,NaN,NaN,NaN,NaN
2,DOLNOŚLĄSKIE,NaN,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14126.0,6259.0,NaN,3786.0,ogółem,NaN,NaN,NaN,NaN,NaN
3,DOLNOŚLĄSKIE,NaN,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14943.0,6145.0,"1593,7",3293.0,ogółem,NaN,NaN,NaN,24.5,-
4,DOLNOŚLĄSKIE,NaN,2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14332.0,5661.0,"1635,9",3129.0,ogółem,NaN,NaN,5.8,36.4,114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454,ŚWIĘTOKRZYSKIE,"5262,19",2021,2.6,18087.0,12.8,3.88,27,2.45,26.4,...,3902.0,2989.0,"1799,3",5602.0,ogółem,1610.0,3762.0,1.7,37.9,141
455,ŚWIĘTOKRZYSKIE,"5782,60",2022,2.1,13958.0,13.6,3.82,26.6,2.73,26.9,...,3811.0,2938.0,"1869,9",6701.0,ogółem,1455.0,3521.0,1.6,37.3,138
456,ŚWIĘTOKRZYSKIE,"6585,16",2023,1.9,12783.0,13.1,3.74,25.5,2.93,29.2,...,3652.0,2695.0,"1931,6",8157.0,ogółem,1592.0,3725.0,1.7,37.4,133
457,ŚWIĘTOKRZYSKIE,"7664,18",2024,1.9,12511.0,13.2,4.15,25.3,3.22,30.8,...,3893.0,2980.0,"2002,1",7967.0,ogółem,1378.0,3465.0,2.1,40.9,134
458,ŚWIĘTOKRZYSKIE,NaN,2025,NaN,13782.0,-,-,-,-,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.8,NaN

In [20]:
df_merged.to_csv('data/processed/merged_data.csv', index=False)

In [21]:
df_merged.describe()

,rok,bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym,ogółem,saldo_migracji_ogółem,wymeldowania_do_miast_ogółem,wymeldowania_na_wieś_ogółem,wymeldowania_ogółem_kobiety,wymeldowania_ogółem_mężczyźni,wymeldowania_ogółem_ogółem,zameldowania_ogółem_kobiety,zameldowania_ogółem_mężczyźni,zameldowania_ogółem_ogółem,zameldowania_z_miast_ogółem,zameldowania_ze_wsi_ogółem,inwestycje_zl,uczelnie niepubliczne,uczelnie publiczne,podmiot_z_udzialem_kap_zagranicznego_na_10_tys_mieszkancow,mieszkania oddane do użytkowania na 10 tys. ludności
count,459.000000,187.000000,3.400000e+02,442.000000,425.000000,425.000000,442.000000,442.000000,442.000000,442.000000,442.000000,442.000000,425.000000,425.000000,400.000000,176.000000,176.000000,374.000000,408.000000
mean,2012.000000,2.003209,6.431399e+04,0.000000,20965.350588,14551.552941,18910.307692,16648.162896,35558.470588,18910.307692,16648.162896,35558.470588,23748.009412,11768.894118,5793.050000,4949.494318,13537.625000,4.903209,40.438235
std,7.797379,0.822526,1.334645e+05,3806.951406,39957.536044,27725.167097,35954.818608,31673.705158,67621.909719,36184.521738,31840.862626,68018.477858,45628.568850,22424.892698,2919.966917,5200.141012,11247.020383,3.621857,16.219400
min,1999.000000,0.600000,4.199000e+03,-6495.000000,3397.000000,2445.000000,3165.000000,2849.000000,6038.000000,2779.000000,2431.000000,5228.000000,2977.000000,2088.000000,1572.000000,0.000000,0.000000,0.700000,11.000000
25%,2005.000000,1.400000,1.907600e+04,-2167.500000,7709.000000,4592.000000,6708.000000,5667.250000,12457.000000,5415.500000,4713.250000,10201.750000,6043.000000,4052.000000,3597.500000,1381.750000,5708.250000,2.300000,28.825000
50%,2012.000000,1.900000,3.088300e+04,-944.500000,10056.000000,7409.000000,9431.000000,8239.500000,17732.500000,8211.500000,7358.000000,15552.000000,9907.000000,5839.000000,5424.500000,4289.500000,10841.000000,4.300000,37.750000
75%,2019.000000,2.500000,4.859425e+04,1382.500000,12973.000000,11112.000000,12501.000000,11274.000000,23663.750000,13855.000000,12297.750000,26132.000000,17669.000000,7814.000000,7280.500000,6961.750000,19253.500000,6.200000,50.825000
max,2025.000000,4.600000,1.139446e+06,16268.000000,209034.000000,151851.000000,191385.000000,169500.000000,360885.000000,191385.000000,169500.000000,360885.000000,243957.000000,118987.000000,20911.000000,27383.000000,48316.000000,21.100000,92.300000

In [22]:
df_merged.missing_values = df_merged.isnull().sum()
display(df_merged.missing_values)

C:\Users\user\AppData\Local\Temp\ipykernel_5072\2790110925.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_merged.missing_values = df_merged.isnull().sum()

region                                                                                            0
wynagrodzenie                                                                                   283
rok                                                                                               0
bezrobotni_w_liczbie_ludności_w_wieku_produkcyjnym                                              272
ogółem                                                                                          119
gimnazjalne,_podstawowe_i_niższe_ogółem_wartość_liczbowa                                        187
gimnazjalne,_podstawowe_i_niższe_ogółem_wskaźnik_precyzji                                       187
policealne_oraz_średnie_zawodowe/branżowe_ogółem_wartość_liczbowa                               187
policealne_oraz_średnie_zawodowe/branżowe_ogółem_wskaźnik_precyzji                              187
wyższe_ogółem_wartość_liczbowa                                                                  187
wyższe_ogółem_wskaźnik_precyzji                                                                 187
zasadnicze_zawodowe/branżowe_ogółem_wartość_liczbowa                                            187
zasadnicze_zawodowe/branżowe_ogółem_wskaźnik_precyzji                                           187
średnie_(łącznie_z_zasadniczym_zawodowym/branżowym_i_policealnym)_ogółem_wartość_liczbowa       187
średnie_(łącznie_ze_średnim_zawodowym/branżowym_i_ogólnokształcącym)_ogółem_wartość_liczbowa    187
średnie_ogólnokształcące_ogółem_wartość_liczbowa                                                187
średnie_ogólnokształcące_ogółem_wskaźnik_precyzji                                               187
średnie_zawodowe/branżowe_ogółem_wartość_liczbowa                                               187
średnie_zawodowe/branżowe_ogółem_wskaźnik_precyzji                                              187
saldo_migracji_ogółem                                                                            17
wymeldowania_do_miast_ogółem                                                                     34
wymeldowania_na_wieś_ogółem                                                                      34
wymeldowania_ogółem_kobiety                                                                      17
wymeldowania_ogółem_mężczyźni                                                                    17
wymeldowania_ogółem_ogółem                                                                       17
zameldowania_ogółem_kobiety                                                                      17
zameldowania_ogółem_mężczyźni                                                                    17
zameldowania_ogółem_ogółem                                                                       17
zameldowania_z_miast_ogółem                                                                      34
zameldowania_ze_wsi_ogółem                                                                       34
liczba_pomiotow_gospodarczych                                                                    91
inwestycje_zl                                                                                    59
typ_inwestycji                                                                                   59
uczelnie niepubliczne                                                                           283
uczelnie publiczne                                                                              283
podmiot_z_udzialem_kap_zagranicznego_na_10_tys_mieszkancow                                       85
mieszkania oddane do użytkowania na 10 tys. ludności                                             51
podmiot_nowo_zarejestr_na_10_tys_ludnosci_w_wieku_produkcyjnym                                   68
dtype: int64